fixtures:
  forge_modules:
    ntp:
      repo: "puppetlabs/ntp"
      ref: "4.1.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.9.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.4.2"
    r10k:
      repo: "zack/r10k"
      ref: "3.1.1"
    motd:
      repo: "saz/motd"
      ref: "2.3.1"
    vim:
      repo: "saz/vim"
      ref: "2.4.0"
    sudo:
      repo: "saz/sudo"
      ref: "3.1.0"
    bash_user_skel:
      repo: "geoffwilliams/bash_user_skel"
      ref: "0.1.0"
    pe_repo:
      repo: "geoffwilliams/pe_repo"
      ref: "0.1.0"
    puppet_enterprise:
      repo: "geoffwilliams/puppet_enterprise"
      ref:  "0.4.3"
  repositories:
    hiera:
      repo: "https://github.com/GeoffWilliams/puppet-hiera"
      branch: "double_gem"
    mcollective_user: "https://github.com/GeoffWilliams/geoffwilliams-mcollective_user"
    puppet_enterprise: "https://github.com/GeoffWilliams/geoffwilliams-puppet_enterprise"
    r_profile: "https://github.com/GeoffWilliams/r_profile"
  symlinks:
    role: "#{source_dir}/site/role"
    profile: "#{source_dir}/site/profile"

